### PR TITLE
Adds a new Appender for syslog

### LINKED ISSUE #26: Syslog appender
Hey, I'm the author of the [**rsyslog**](https://github.com/atheriel/rsyslog) package. I'm wondering if you're interested in including a syslog appender. If so, I'd be happy to write it.

### PR DESCRIPTION
**Pull request by atheriel**
I've put together a pretty basic appender for syslog, including documentation. I've added `rsyslog` to Suggests and gated a few things with `requireNamespace()`, so it should signal a useful error if the user does not have the correct package installed.

You can test that it works with the provided example with `journalctl -t myapp` (on Linux).

Let me know if it looks OK, or what I can do to improve it.

Closes #26.

### CODE REVIEW

**Comment by s-fleck** [comment]
Thanks looks good. 

One of the key features of lgr is support for logging data as computer readable fields (see https://s-fleck.github.io/lgr/articles/lgr.html#custom-fields for an example)

AFAIK syslog also supports logging key-value pairs (also called "structured data"), though I do not know how widely that is supported. Would you have any idea about how to add support for that?

**Comment by atheriel** [comment]
The short answer is: no, it's not widely supported, or really supported at all. In this particular case, custom fields should probably be handled by the Layout -- is that currently possible?

Long answer: structured data was part of RFC [5424](https://tools.ietf.org/html/rfc5424) (2009) but **not** part of the original BSD implementation (1980; informally described in RFC [3164](https://tools.ietf.org/html/rfc3164)), which is what systems tend to emulate.

After the publication of RFC 5424, it quickly became apparent that structured log messages were better left to well-known formats, e.g. JSON, which would be more easily backwards-compatible with pre-5424 implementations. BSD syslog turns 40 (!) next year, so this backwards compatibility carries some weight.

For this reason, the original author of the syslog RFCs regards structured data as ["dead on arrival"](https://lists.gt.net/rsyslog/users/6361).

Further, existing implementations of syslog (for example, [under Linux](http://man7.org/linux/man-pages/man3/syslog.3.html)) do not support structured data, which the *actual* reason why `rsyslog` does not, either. The same is true of other popular language implementations, for example Python's [syslog module](https://docs.python.org/3.7/library/syslog.html).

**Comment by s-fleck** [comment]
Ok thanks for the writeup. I'll see that I get around integrating the pull request over the weekend :). If the structured data just gets appended to the log message or something, it can easily be handled by a Layout. In fact the `%f`/`%j` tokens for LayoutFormat format strings already do something very similar.

**Comment by s-fleck** [comment]
I've merge the Appender but I will probably still have a few questions for you. This first one that comes to mind:

Just so that I understand, rsyslog keeps a single open syslog connection? And it does not need to be closed? I am tempted to move `open_syslog()`, `set_syslog_mask()` and `close_syslog()` all to `$append()` so it doesn't interfere with other rsyslog instances.

**Comment by atheriel** [comment]
> Just so that I understand, rsyslog keeps a single open syslog connection? And it does not need to be closed? I am tempted to move open_syslog(), set_syslog_mask() and close_syslog() all to $append() so it doesn't interfere with other rsyslog instances.

I'm fairly sure that a process can only have a single syslog identifier. If you call `open_syslog()` it replaces the existing configuration. So it is not possible to prevent it from interfering with another syslog appender.

The connection does not need to be closed manually, I think it just frees up system resources when you do so.

> can rsyslog also handle vectors of messages and log levels, or do I have to wrap it in mapply() to enable vectorized logging?

You will have to use `mapply()`.

> are syslog level keywords case sensitive?

They are at the moment (following the RFCs), but I'd be open to changing that.

> I modified $append() so that it uses the logger name as identifier, if no identifier is supplied when initializing the appender; is this a sensible default in your oppionion?

That makes sense to me!

**Comment by s-fleck** [comment]
Ok thanks that clears it up :) Don't worry about the log levels... just one more thing, to you know of a reliable way to read the syslog? the journalctl does not work on travis (i think its systemd specific?)
can i just do something like `cat var/log/syslog` or does that have some disadvantages?

**Comment by dselivanov** [comment]
Btw there is syslog compatible producer which can send logs to local sockets, tcp, udp destinations - https://github.com/s-u/ulog. I've used it and was quite happy. One issue - [I wasn't able ta make it work with tcp](https://github.com/s-u/ulog/issues/3)...

**Comment by s-fleck** [comment]
thanks for the tip, ill take a look at it!

**Comment by atheriel** [comment]
@dselivanov I'm wondering if there are features of `ulog` that could be incorporated into the `rsyslog` package. When does it make sense to send logs directly over tcp/udp instead of forwarding them with the syslog daemon?

**Comment by s-fleck** [comment]
@atheriel If i understand it correctly, rsyslog only supports logging to a local syslog, while ulog supports logging directly to a remote log server.

**Comment by dselivanov** [comment]
@atheriel yeah, in my case I wanted to easily log to remote server (and this is easy with ulog - you don't need any additional setup for the application). 

But I ended up sending logs to the local `rsyslog` (not confuse to your pkg) and forwarding to remote central `rsyslog`. Reason is that rsyslog handles a lot of edge cases for you (such as collection of messages in case of network break, forwarding to multiple destinations, etc). But I like simplicity of the ulog for hassle free logging to a remote server.

**Pull request merged**
